#!/bin/bash
EULA=`cat /opt/pt/eula730.txt`
EULAACCEPTED="/EULA-Accepted"

if [[ ! -f $EULAACCEPTED ]]; then
   /usr/bin/whiptail --msgbox "$EULA" 30 75 --backtitle "This Virtual Machine comes with Cisco Packet Tracer preinstalled." --title "Please read the Cicso Packet Tracer EULA" --scrolltext

   /usr/bin/whiptail --yesno  "$EULA" 30 75 --defaultno --yes-button "I Agree" --no-button "I Do Not Agree" --backtitle "This Virtual Machine comes with Cisco Packet Tracer preinstalled." --title "Do you agree the Cisco Packet Tracer EULA?"

   if [[ "$?" != "0" ]];
     then
	whiptail --msgbox "
You cannot continue using this Virtual Machine without agreeing to the Cisco Packet Tracer EULA.
The Virtual Machine will now be turned off.
	" 30 75
        poweroff
	exit
   fi
   touch $EULAACCEPTED
fi

